CREATE TABLE "ASSET" (
	"NUMBER" INTEGER,
	"PATH1" TEXT,
	"PATH2" TEXT,
	"PATH3" TEXT,
	"PATH4" TEXT,

	"NAME" TEXT NOT NULL,
	"ALIAS" TEXT,
	"SINCE" TEXT,
	"PRICE_VALUE" NUMBER ,
	"PRICE_CURRENCY" TEXT,

	"NOTE" TEXT DEFAULT '',
	"IN_GROUP" TEXT,
	"ADDED_ON" TEXT,
	PRIMARY KEY("NUMBER" AUTOINCREMENT)
)